/* ==================================================
   STAR ACADEMY
   NOUVELLE BASE
   ================================================== */


/* ==================================================
   TABLE DES PARTICIPANTES
   ================================================== */

create table if not exists public.players (

  id bigint generated by default as identity
    primary key,

  created_at timestamptz
    default now(),

  name text not null unique

);


/* ==================================================
   TABLE DES CANDIDATS
   ================================================== */

create table if not exists public.students (

  id bigint generated by default as identity
    primary key,

  created_at timestamptz
    default now(),

  name text not null unique

);


/* ==================================================
   TABLE DES PRONOSTICS
   ================================================== */

create table if not exists public.predictions (

  id bigint generated by default as identity
    primary key,

  created_at timestamptz
    default now(),

  player_name text not null,

  prime_number integer not null,

  immunity text,

  best_duo text,

  best_performance text,

  favorite text,

  eliminated text,

  winner text,

  points integer default 0

);


/* ==================================================
   EMPÊCHER UN DOUBLE PRONOSTIC
   POUR UNE MÊME PERSONNE ET UN MÊME PRIME
   ================================================== */

create unique index
if not exists predictions_player_prime_unique

on public.predictions (
  player_name,
  prime_number
);


/* ==================================================
   ACTIVER LA SÉCURITÉ
   ================================================== */

alter table public.players
enable row level security;

alter table public.students
enable row level security;

alter table public.predictions
enable row level security;


/* ==================================================
   POLITIQUES — PARTICIPANTES
   ================================================== */

create policy
"Lecture participantes"

on public.players

for select

to anon, authenticated

using (true);


create policy
"Ajout participantes"

on public.players

for insert

to anon, authenticated

with check (true);


create policy
"Modification participantes"

on public.players

for update

to anon, authenticated

using (true)

with check (true);


/* ==================================================
   POLITIQUES — CANDIDATS
   ================================================== */

create policy
"Lecture candidats"

on public.students

for select

to anon, authenticated

using (true);


create policy
"Ajout candidats"

on public.students

for insert

to anon, authenticated

with check (true);


create policy
"Modification candidats"

on public.students

for update

to anon, authenticated

using (true)

with check (true);


create policy
"Suppression candidats"

on public.students

for delete

to anon, authenticated

using (true);


/* ==================================================
   POLITIQUES — PRONOSTICS
   ================================================== */

create policy
"Lecture pronostics"

on public.predictions

for select

to anon, authenticated

using (true);


create policy
"Ajout pronostics"

on public.predictions

for insert

to anon, authenticated

with check (true);


create policy
"Modification pronostics"

on public.predictions

for update

to anon, authenticated

using (true)

with check (true);