/* ==================================================
   STAR ACADEMY — BASE SUPABASE
   ================================================== */


/* ==================================================
   TABLE DES PRONOSTICS
   ================================================== */

create table if not exists public.predictions (

  id bigint generated by default as identity
    primary key,

  created_at timestamptz
    default now(),

  player_name text not null,

  prime_number integer not null,

  immunity text,

  best_duo text,

  best_performance text,

  favorite text,

  eliminated text,

  winner text,

  points integer default 0

);


/* ==================================================
   ÉVITER LES DOUBLONS
   ================================================== */

create unique index
if not exists predictions_player_prime_unique
on public.predictions (
  player_name,
  prime_number
);


/* ==================================================
   RLS
   ================================================== */

alter table public.predictions
enable row level security;


/* ==================================================
   LECTURE
   ================================================== */

create policy
"Autoriser la lecture des pronostics"

on public.predictions

for select

to anon, authenticated

using (true);


/* ==================================================
   AJOUT
   ================================================== */

create policy
"Autoriser l'ajout des pronostics"

on public.predictions

for insert

to anon, authenticated

with check (true);


/* ==================================================
   MODIFICATION
   ================================================== */

create policy
"Autoriser la modification des pronostics"

on public.predictions

for update

to anon, authenticated

using (true)

with check (true);